ALTER TABLE SUPPLIERS DROP CONSTRAINT SUPP_FK_1;
ALTER TABLE SUPPLIERS DROP CONSTRAINT SUPP_FK_2;
ALTER TABLE DRUG DROP CONSTRAINT DRG_FK_1;
ALTER TABLE STOCK DROP CONSTRAINT ST_FK_1;
ALTER TABLE STOCK DROP CONSTRAINT ST_FK_2;
ALTER TABLE STOCK DROP CONSTRAINT STK_FK_3;
ALTER TABLE STOCK DROP CONSTRAINT STK_FK_4;
ALTER TABLE INCOME DROP CONSTRAINT IN_FK;
ALTER TABLE OUTCOME DROP CONSTRAINT OUT_FK;
ALTER TABLE INVENTORY DROP CONSTRAINT INV_FK;
ALTER TABLE EMPLOYEE DROP CONSTRAINT EMP_FK;

DROP TABLE DRUG_COMP;
DROP TABLE DRUG_SUPP;
DROP TABLE SUPPLIERS;
DROP TABLE DRUG;
DROP TABLE STOCK;
DROP TABLE INCOME;
DROP TABLE OUTCOME;
DROP TABLE PHARMACY;
DROP TABLE INVENTORY;
DROP TABLE EMPLOYEE;

ALTER SESSION SET nls_language='ENGLISH';
ALTER SESSION SET nls_date_format='DD-MON-YYYY';

-- Tag: DC
CREATE TABLE DRUG_COMP 
    (DC_ID NUMBER(11) NOT NULL, 
    DC_NAME VARCHAR2(20) NOT NULL, 
    DC_ADDRESS VARCHAR2(100),
    CONSTRAINT DC_PK PRIMARY KEY(DC_ID) USING INDEX ENABLE);

-- Tag: DS
CREATE TABLE DRUG_SUPP
    (DS_ID NUMBER(11) NOT NULL,
    DS_NAME VARCHAR2(20) NOT NULL, 
    DS_ADDRESS VARCHAR2(100),
    CONSTRAINT DS_PK PRIMARY KEY(DS_ID) USING INDEX ENABLE);

-- Tag: SUPP
CREATE TABLE SUPPLIERS 
    (SUPP_ID NUMBER(11) NOT NULL, 
    DS_ID NUMBER(11) NOT NULL,
    DRG_ID NUMBER(11) NOT NULL,
    CONSTRAINT SUPP_PK PRIMARY KEY(SUPP_ID) USING INDEX ENABLE);

-- Tag: DRG
CREATE TABLE DRUG
    (DRG_ID NUMBER(13,0) NOT NULL,
    DRG_NAME VARCHAR2(35) NOT NULL,
    DRG_TYPE VARCHAR2(15) NOT NULL,
    DC_ID NUMBER(13,0) NOT NULL,
    CONSTRAINT DRG_PK PRIMARY KEY (DRG_ID) USING INDEX ENABLE);

-- Tag: STK
CREATE TABLE STOCK
    (ST_ID NUMBER(11) NOT NULL,
    ST_BUY_PRICE NUMBER(6,2) NOT NULL,
    ST_EXPIRE DATE NOT NULL,
    ST_SELL_PRICE NUMBER(6,2) NOT NULL,
    INV_ID NUMBER(11) NOT NULL,
    IN_ID NUMBER(11),
    OUT_ID NUMBER(11) NOT NULL,
    DRG_ID NUMBER(11) NOT NULL,
    CONSTRAINT ST_PK PRIMARY KEY (ST_ID) USING INDEX ENABLE);

-- Tag: IN
CREATE TABLE INCOME
    (IN_ID NUMBER(11) NOT NULL,
    IN_DATE DATE NOT NULL,
    PH_ID NUMBER(11),
    CONSTRAINT IN_PK PRIMARY KEY(IN_ID) USING INDEX ENABLE);

-- Tag: OUT
CREATE TABLE OUTCOME
    (OUT_ID NUMBER(11) NOT NULL,
    OUT_DATE DATE NOT NULL,
    PH_ID NUMBER(11),
    CONSTRAINT OUT_PK PRIMARY KEY(OUT_ID) USING INDEX ENABLE);

-- Tag: PHA
CREATE TABLE PHARMACY
    (PH_ID NUMBER(11) NOT NULL,
    PH_NAME VARCHAR2(15),
    PH_ADDRESS VARCHAR2(100),
    PH_PHONE VARCHAR2(16),
    CONSTRAINT PH_PK PRIMARY KEY(PH_ID) USING INDEX ENABLE);

-- Tag: INV
CREATE TABLE INVENTORY
    (INV_ID NUMBER(11) NOT NULL,
    PH_ID NUMBER(11) NOT NULL,
    CONSTRAINT INV_PK PRIMARY KEY (INV_ID) USING INDEX ENABLE);
    
-- Tag: EMP
CREATE TABLE EMPLOYEE 
    (EMP_ID NUMBER(11) NOT NULL,
    EMP_NAME VARCHAR2(200),
    EMP_PHONE VARCHAR2(16),
    EMP_SAL NUMBER(6,2),
    PH_ID NUMBER(11) NOT NULL,
    CONSTRAINT EMP_PK PRIMARY KEY(EMP_ID) USING INDEX ENABLE);
    

-- Foreign Key References
ALTER TABLE SUPPLIERS ADD CONSTRAINT SUPP_FK_1
    FOREIGN KEY (DS_ID) REFERENCES DRUG_SUPP(DS_ID);

ALTER TABLE SUPPLIERS ADD CONSTRAINT SUPP_FK_2
    FOREIGN KEY (DRG_ID) REFERENCES DRUG(DRG_ID);

ALTER TABLE DRUG ADD CONSTRAINT DRG_FK_1
    FOREIGN KEY (DC_ID) REFERENCES DRUG_COMP(DC_ID);

ALTER TABLE STOCK ADD CONSTRAINT ST_FK_1
    FOREIGN KEY (INV_ID) REFERENCES INVENTORY(INV_ID);

ALTER TABLE STOCK ADD CONSTRAINT ST_FK_2
    FOREIGN KEY (IN_ID) REFERENCES INCOME(IN_ID);

ALTER TABLE STOCK ADD CONSTRAINT STK_FK_3
    FOREIGN KEY (OUT_ID) REFERENCES OUTCOME(OUT_ID);

ALTER TABLE STOCK ADD CONSTRAINT STK_FK_4
    FOREIGN KEY (DRG_ID) REFERENCES DRUG(DRG_ID);
    
ALTER TABLE INCOME ADD CONSTRAINT IN_FK
    FOREIGN KEY (PH_ID) REFERENCES PHARMACY(PH_ID);

ALTER TABLE OUTCOME ADD CONSTRAINT OUT_FK
    FOREIGN KEY (PH_ID) REFERENCES PHARMACY(PH_ID);

ALTER TABLE INVENTORY ADD CONSTRAINT INV_FK
    FOREIGN KEY (PH_ID) REFERENCES PHARMACY(PH_ID);

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMP_FK
    FOREIGN KEY (PH_ID) REFERENCES PHARMACY(PH_ID);